name: Dispatch Deployment Command (PR Deployment)

on:
  issue_comment:
    types:
      - created

jobs:
  dispatch-deployment-command:
    if: github.event.issue.pull_request
    name: Send Deployment command
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        id: get-pr-info
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commands: |
            deploy
          reactions: true
          issue-type: pull-request
          static-args: |
            branch=${{ fromJSON(steps.get-pr-info.outputs.result).head.ref }}
            comment-id=${{ github.event.comment.id }}
