name: Slack verify

on:
  repository_dispatch:
    types:
      - verify

jobs:

  integrity:
    name: Integrity Check
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}

    steps:

      #
      # Identify target server
      #
      - name: Validate Origin
        uses: actions/github-script@v3
        id: validate-origin
        env:
          AGENT: ${{ github.event.client_payload.integrity.agent }}
          BODY: ${{ github.event.client_payload.integrity.body }}
          TIMESTAMP: ${{ github.event.client_payload.integrity.timestamp }}
          SIGNATURE: ${{ github.event.client_payload.integrity.signature }}
          SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        with:
          result-encoding: string
          script: |
            if(!`${process.env.AGENT}`.startsWith("Slackbot")){
                core.setFailed("User agent mismatch.")
            } else {
                const base = `v0:${process.env.TIMESTAMP}:${process.env.BODY}`
                const hash = require('crypto').createHmac('sha256', `${process.env.SIGNING_SECRET}`).update(base).digest("hex")
                if(`${process.env.SIGNATURE}` !== `v0=${hash}`) {
                  core.setFailed("Request integrity failed.")
                } 
            }
            
  build:
    name: Build Commit
    needs: integrity
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}

    steps:

      #
      # Identify target server
      #
      - name: Build Dummy
        run: echo "hello"
